# Generated by Django 3.2.5 on 2021-07-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_app', '0003_python_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='python',
            name='slug',
        ),
    ]
